/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_final;

import java.awt.Toolkit;



/**
 *
 * @author Acer
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu1() {
        initComponents();
        //this.setResizable(false);
        setTitle("Cafe de` Pablo");
               setAlwaysOnTop(true);
        setResizable(false);
        setVisible(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
        
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        
        
        setSize(x,y);
    }
    
    public void close(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        Vege = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Burger = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Milk = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Coffee = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Chicken = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Seafood = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Soups = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Appertizers = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        menu_home = new javax.swing.JButton();
        menu_back = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/back-button.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafe de` Pablo");
        getContentPane().setLayout(null);

        Vege.setBackground(new java.awt.Color(0, 0, 0));
        Vege.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/7878bf6527144ba19488447c7b4759a1.png"))); // NOI18N
        Vege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegeActionPerformed(evt);
            }
        });
        getContentPane().add(Vege);
        Vege.setBounds(110, 740, 290, 230);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VEGETARIAN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 700, 164, 29);

        Burger.setBackground(new java.awt.Color(0, 0, 0));
        Burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/18COOKING-MCBITTYBEANBURGERS2-articleLarge.png"))); // NOI18N
        Burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerActionPerformed(evt);
            }
        });
        getContentPane().add(Burger);
        Burger.setBounds(520, 740, 290, 230);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BURGERS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 670, 116, 29);

        Milk.setBackground(new java.awt.Color(0, 0, 0));
        Milk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/1371609102889.png"))); // NOI18N
        Milk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkActionPerformed(evt);
            }
        });
        getContentPane().add(Milk);
        Milk.setBounds(1020, 750, 320, 220);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MILK SHAKES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1121, 606, 170, 29);

        Coffee.setBackground(new java.awt.Color(0, 0, 0));
        Coffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/coffe.png"))); // NOI18N
        Coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeActionPerformed(evt);
            }
        });
        getContentPane().add(Coffee);
        Coffee.setBounds(1500, 750, 310, 220);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COFFEE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1630, 640, 95, 29);

        Chicken.setBackground(new java.awt.Color(0, 0, 0));
        Chicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/baked-lemon-chicken-6.png"))); // NOI18N
        Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenActionPerformed(evt);
            }
        });
        getContentPane().add(Chicken);
        Chicken.setBounds(510, 370, 310, 210);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CHICKEN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(666, 320, 113, 29);

        Seafood.setBackground(new java.awt.Color(0, 0, 0));
        Seafood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/Fotolia_27246788_Subscription_XL.png"))); // NOI18N
        Seafood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeafoodActionPerformed(evt);
            }
        });
        getContentPane().add(Seafood);
        Seafood.setBounds(1500, 367, 310, 203);

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SOUPS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1161, 320, 78, 29);

        Soups.setBackground(new java.awt.Color(0, 0, 0));
        Soups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/vegetable-soup-7.png"))); // NOI18N
        Soups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoupsActionPerformed(evt);
            }
        });
        getContentPane().add(Soups);
        Soups.setBounds(1010, 370, 330, 210);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APPERTIZERS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 320, 167, 29);

        Appertizers.setBackground(new java.awt.Color(0, 0, 0));
        Appertizers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/baked prosciutto & brie with apple butter.png"))); // NOI18N
        Appertizers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppertizersActionPerformed(evt);
            }
        });
        getContentPane().add(Appertizers);
        Appertizers.setBounds(110, 370, 290, 220);

        jPanel3.setBackground(new java.awt.Color(132, 132, 130));

        menu_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/home.png"))); // NOI18N
        menu_home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menu_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_homeActionPerformed(evt);
            }
        });

        menu_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/left-arrow.png"))); // NOI18N
        menu_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menu_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_backActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/arrow-pointing-to-right.png"))); // NOI18N
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel10.setText("Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1692, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1975, 52);

        jLabel11.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SEAFOOD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1600, 310, 116, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/menu.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(870, 110, 147, 155);

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/k.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -200, 2200, 1410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void SeafoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeafoodActionPerformed
        Seafood s=new Seafood();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_SeafoodActionPerformed

    private void AppertizersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppertizersActionPerformed
        Appertizers s=new Appertizers();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_AppertizersActionPerformed

    private void ChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenActionPerformed
        Chicken s=new Chicken();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_ChickenActionPerformed

    private void VegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegeActionPerformed
        vege s=new vege();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_VegeActionPerformed

    private void BurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerActionPerformed
        Burger s=new Burger();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_BurgerActionPerformed

    private void MilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkActionPerformed
        Milkshake s=new Milkshake();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_MilkActionPerformed

    private void CoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeActionPerformed
        Coffe s=new Coffe();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_CoffeeActionPerformed

    private void SoupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoupsActionPerformed
        Soups s=new Soups();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_SoupsActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void menu_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_backActionPerformed
        NewJFrame s= new NewJFrame();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_menu_backActionPerformed

    private void menu_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_homeActionPerformed
        NewJFrame s= new NewJFrame();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_menu_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appertizers;
    private javax.swing.JButton Burger;
    private javax.swing.JButton Chicken;
    private javax.swing.JButton Coffee;
    private javax.swing.JButton Milk;
    private javax.swing.JButton Seafood;
    private javax.swing.JButton Soups;
    private javax.swing.JButton Vege;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton menu_back;
    private javax.swing.JButton menu_home;
    // End of variables declaration//GEN-END:variables
}
